- hosts: all
  tasks:
    - name: /tmp/ansible_was_here
      ansible.builtin.file:
        path: /tmp/my.conf
        state: touch

    # - file: 
    #   state: touch
    #   owner: root
    #   group: root
    #   mode: 0600
    #   become: yes